name: DAST - ZAP Security Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Scan
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
        run: |
          chmod -R 777 ./
          docker run \
            -v "$(pwd):/zap/wrk/:rw" \
            -e TARGET_URL="${TARGET_URL}" \
            -e SUBSCRIPTION_KEY="${SUBSCRIPTION_KEY}" \
            -t zaproxy/zap-stable \
            zap.sh -cmd -autorun /zap/wrk/security/zap.yml

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
